export type IdentityApplicationErrorCode =
  | 'INVALID_CREDENTIALS'
  | 'IDENTITY_SUSPENDED'
  | 'EMAIL_VERIFICATION_REQUIRED'
  | 'SESSION_INVALID'
  | 'SESSION_REVOKED'
  | 'REFRESH_TOKEN_INVALID'
  | 'REFRESH_TOKEN_EXPIRED'
  | 'REFRESH_TOKEN_REUSED'
  | 'REGISTRATION_CONFLICT'
  | 'PASSWORD_POLICY_VIOLATION'
  | 'AUTHENTICATION_TRANSACTION_FAILED'
  | 'EMAIL_ALREADY_VERIFIED'
  | 'EMAIL_VERIFICATION_TOKEN_INVALID'
  | 'EMAIL_VERIFICATION_TOKEN_EXPIRED'
  | 'EMAIL_VERIFICATION_TOKEN_CONSUMED'
  | 'EMAIL_VERIFICATION_REQUEST_THROTTLED'
  | 'EMAIL_VERIFICATION_NOT_ALLOWED'
  | 'EMAIL_VERIFICATION_TRANSACTION_FAILED'
  | 'PASSWORD_RESET_TOKEN_INVALID'
  | 'PASSWORD_RESET_TOKEN_EXPIRED'
  | 'PASSWORD_RESET_TOKEN_CONSUMED'
  | 'PASSWORD_RESET_REQUEST_THROTTLED'
  | 'PASSWORD_RESET_NOT_ALLOWED'
  | 'PASSWORD_REUSE_NOT_ALLOWED'
  | 'PASSWORD_RESET_TRANSACTION_FAILED';

export class IdentityApplicationError extends Error {
  constructor(
    public readonly code: IdentityApplicationErrorCode,
    message: string,
  ) {
    super(message);
    this.name = 'IdentityApplicationError';
  }
}
